services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama_rag
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    networks:
      - rag-network
    restart: unless-stopped

  rag_api:
    build:
      context: .
    container_name: rag_api_new
    ports:
      - "8000:8000"
    depends_on:
      - ollama
    environment:
      - OLLAMA_URL=http://ollama_rag:11434
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    networks:
      - rag-network
    restart: unless-stopped

  streamlit_app:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: streamlit_app_new
    ports:
      - "8501:8501"
    depends_on:
      - rag_api
      - ollama
    environment:
      - OLLAMA_URL=http://ollama_rag:11434
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    networks:
      - rag-network
    restart: unless-stopped

volumes:
  ollama_data:

networks:
  rag-network:
    driver: bridge
